import React from 'react'
import { getRecommendations } from '../actions/ai-actions'
import { RecommendationCard } from '../components/ai/RecommendationCard'
import { Bot, Sparkles } from 'lucide-react'

export const metadata = {
  title: 'AI Recommendation Center | Cirqle',
}

export default async function AICenterPage() {
  const recommendations = await getRecommendations()

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight flex items-center">
            <Bot className="w-8 h-8 mr-3 text-indigo-500" />
            AI Recommendation Center
          </h1>
          <p className="text-slate-500 mt-2">
            Intelligent insights and automated optimizations generated by your personalized AI models.
          </p>
        </div>
        <div className="px-4 py-2 bg-indigo-50 dark:bg-indigo-900/30 rounded-full flex items-center border border-indigo-100 dark:border-indigo-800">
          <Sparkles className="w-4 h-4 text-indigo-500 mr-2" />
          <span className="text-sm font-medium text-indigo-700 dark:text-indigo-700 dark:text-indigo-300">
            {recommendations.length} Active Insights
          </span>
        </div>
      </div>

      {recommendations.length === 0 ? (
        <div className="flex flex-col items-center justify-center p-12 bg-white dark:bg-slate-900 rounded-xl border border-dashed border-slate-200 dark:border-slate-800">
          <Bot className="w-12 h-12 text-slate-700 dark:text-slate-300 mb-4" />
          <h3 className="text-lg font-medium text-slate-900 dark:text-slate-100">You're all caught up!</h3>
          <p className="text-slate-500 mt-1">Our AI is monitoring your campaigns. We'll alert you when there are new recommendations.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
          {recommendations.map((rec: any) => (
            <RecommendationCard 
              key={rec.id} 
              rec={{
                id: rec.id,
                title: rec.title,
                summary: rec.summary,
                root_cause: rec.root_cause,
                business_impact: rec.business_impact,
                expected_roi: rec.expected_roi,
                estimated_savings: rec.estimated_savings,
                suggested_action: rec.suggested_action,
                confidence: rec.confidence_score,
                priority: rec.priority,
                status: rec.recommendation_status,
                supporting_metrics: rec.supporting_metrics
              }} 
            />
          ))}
        </div>
      )}
    </div>
  )
}
