/**
 * Business Partner statement → standalone HTML, sized for a single mobile-
 * width WhatsApp image (and reused as-is for the one-page PDF export).
 *
 * Independent of src/lib/invoices/render-html.ts by design — this module
 * must not depend on (or be depended on by) any invoice code path.
 */
import type { PartnerStatementData } from './queries'

export const STATEMENT_WIDTH = 640

const fmtAmt = (n: number) => `₹${Math.round(n).toLocaleString('en-IN')}`
const fmtDate = (s: string) => {
  const d = new Date(s)
  return isNaN(d.getTime()) ? s : d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
}

const STATUS_COLOR: Record<string, string> = {
  draft:    '#6b7280',
  sent:     '#2563eb',
  partial:  '#d97706',
  paid:     '#16a34a',
  overdue:  '#dc2626',
}

const STATUS_LABEL: Record<string, string> = {
  draft: 'Draft',
  sent: 'Sent',
  partial: 'Partially Paid',
  paid: 'Paid',
  overdue: 'Overdue',
}

export interface StatementBrand {
  companyName: string
  primaryColor: string
}

/** Full standalone HTML document for the statement (used for rasterizing + printing). */
export function renderPartnerStatementHtml(data: PartnerStatementData, brand: StatementBrand): string {
  const rows = data.rows.map(row => `
    <tr>
      <td style="padding:8px 6px;border-bottom:1px solid #eee;font-size:13px;color:#222;">${escapeHtml(row.clientName)}</td>
      <td style="padding:8px 6px;border-bottom:1px solid #eee;font-size:13px;color:#222;">${escapeHtml(row.invoiceNumber)}</td>
      <td style="padding:8px 6px;border-bottom:1px solid #eee;font-size:13px;color:#222;text-align:right;">${fmtAmt(row.pending)}</td>
      <td style="padding:8px 6px;border-bottom:1px solid #eee;font-size:12px;text-align:right;">
        <span style="color:${STATUS_COLOR[row.status] || '#6b7280'};font-weight:600;">${STATUS_LABEL[row.status] || row.status}</span>
      </td>
    </tr>`).join('')

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, 'Helvetica Neue', Arial, sans-serif; }
  body { width: ${STATEMENT_WIDTH}px; background: #ffffff; }
</style>
</head>
<body>
  <div style="width:${STATEMENT_WIDTH}px;background:#fff;">
    <div style="background:${brand.primaryColor};padding:20px 24px;color:#fff;">
      <div style="font-size:18px;font-weight:700;">${escapeHtml(brand.companyName)}</div>
      <div style="font-size:13px;opacity:0.85;margin-top:2px;">Business Partner Statement</div>
    </div>

    <div style="padding:20px 24px;">
      <div style="font-size:15px;font-weight:600;color:#111;">${escapeHtml(data.partner.name)}</div>
      ${data.partner.company ? `<div style="font-size:12px;color:#666;">${escapeHtml(data.partner.company)}</div>` : ''}
      <div style="font-size:12px;color:#666;margin-top:2px;">Statement Date: ${fmtDate(data.statementDate)}</div>

      <table style="width:100%;border-collapse:collapse;margin-top:16px;">
        <thead>
          <tr>
            <th style="text-align:left;padding:6px;font-size:11px;color:#888;text-transform:uppercase;border-bottom:2px solid #ddd;">Client</th>
            <th style="text-align:left;padding:6px;font-size:11px;color:#888;text-transform:uppercase;border-bottom:2px solid #ddd;">Invoice</th>
            <th style="text-align:right;padding:6px;font-size:11px;color:#888;text-transform:uppercase;border-bottom:2px solid #ddd;">Pending</th>
            <th style="text-align:right;padding:6px;font-size:11px;color:#888;text-transform:uppercase;border-bottom:2px solid #ddd;">Status</th>
          </tr>
        </thead>
        <tbody>
          ${rows || `<tr><td colspan="4" style="padding:16px 6px;font-size:13px;color:#888;text-align:center;">No pending invoices</td></tr>`}
        </tbody>
      </table>

      <div style="margin-top:18px;padding:14px 16px;background:#f8f8fc;border-radius:8px;display:flex;justify-content:space-between;align-items:center;">
        <span style="font-size:13px;color:#555;font-weight:600;">Total Outstanding</span>
        <span style="font-size:18px;color:#111;font-weight:700;">${fmtAmt(data.totalOutstanding)}</span>
      </div>
    </div>

    <div style="padding:12px 24px;border-top:1px solid #eee;text-align:center;">
      <span style="font-size:11px;color:#999;">Generated by Cirqle CRM</span>
    </div>
  </div>
</body>
</html>`
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] as string))
}
